import reflex as rx
from enum import StrEnum

NAV_BG = "#333333"
FINANCIAL_GREY = "#F0F0F0"
POSITIVE_GREEN = "#00A651"
NEGATIVE_RED = "#C00000"
ALERT_AMBER = "#FFC000"
ROW_HIGHLIGHT = "#FFF2CC"
BORDER_GREY = "#CCCCCC"
SIDEBAR_BG = "#F9F9F9"
NAV_HEIGHT = "40px"
KPI_HEIGHT = "28px"
MOVERS_ROW_HEIGHT = "22px"
MOVERS_EXPANDED_HEIGHT = "200px"
CONTROL_BAR_HEIGHT = "36px"
WORKSPACE_SUBTAB_HEIGHT = "28px"
WORKSPACE_GENERATE_BAR_HEIGHT = "40px"
TABLE_ROW_HEIGHT = "28px"
SIDEBAR_WIDTH = "220px"
DEFAULT_FONT = "Inter"
ICON_NAV_SIZE = 14
ICON_KPI_SIZE = 8
ICON_SIDEBAR_CLOSE = 14
ICON_ADD_ALERT = 12